/** Tailwind local para las páginas estáticas de Systemic y MiBillar. */
module.exports = {
  darkMode: 'class',
  content: ['./public/systemic-stitch.html', './public/caso-mibillar.html'],
  theme: {
    extend: {
      colors: {
        primary: '#a5e7ff',
        error: '#ffb4ab',
        secondary: '#d1bcff',
        'on-surface': '#e5e2e1',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-dim': '#131313',
        'on-surface-variant': '#bbc9cf',
        'on-primary': '#003543',
        'primary-fixed': '#b6ebff',
        'primary-fixed-dim': '#47d6ff',
        'secondary-fixed': '#e9ddff',
        'secondary-fixed-dim': '#d1bcff',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-bright': '#3a3939',
        'surface-variant': '#353534',
        surface: '#131313',
        background: '#131313',
        outline: '#859399',
        'outline-variant': '#3c494e',
        tertiary: '#dddddd',
        'tertiary-container': '#c1c1c1',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'container-max': '1440px',
        'margin-mobile': '24px',
        unit: '8px',
        'margin-desktop': '64px',
        gutter: '32px',
      },
      fontFamily: {
        display: ['Syne', 'sans-serif'],
        data: ['JetBrains Mono', 'monospace'],
        'display-xl': ['Syne', 'sans-serif'],
        'data-value': ['JetBrains Mono', 'monospace'],
        'data-label': ['JetBrains Mono', 'monospace'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Syne', 'sans-serif'],
        'headline-lg': ['Syne', 'sans-serif'],
        'display-xl-mobile': ['Syne', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['80px', { lineHeight: '88px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-xl-mobile': ['48px', { lineHeight: '52px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['32px', { lineHeight: '38px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'data-label': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'data-value': ['12px', { lineHeight: '16px', fontWeight: '400' }],
      },
    },
  },
};
